/**
 * Executive Summary Report Template
 *
 * Generates a 5-6 page executive-level accessibility compliance report.
 * Designed for leadership and non-technical stakeholders.
 */

import Handlebars from 'handlebars';
import type { ReportTemplateData } from '../types';
import { REPORT_BASE_CSS } from './base-styles';

/** Handlebars helper for severity CSS class */
Handlebars.registerHelper('severityClass', function (severity: string) {
  return `severity-${severity}`;
});

/** Handlebars helper for delta display */
Handlebars.registerHelper('deltaDisplay', function (delta: number | null) {
  if (delta === null) return '—';
  if (delta > 0) return `↑ ${delta}`;
  if (delta < 0) return `↓ ${Math.abs(delta)}`;
  return '→ 0';
});

/** Handlebars helper for delta class */
Handlebars.registerHelper('deltaClass', function (delta: number | null) {
  if (delta === null) return 'score-delta-unchanged';
  if (delta > 0) return 'score-delta-improved';
  if (delta < 0) return 'score-delta-declined';
  return 'score-delta-unchanged';
});

/** Handlebars helper for compliance status */
Handlebars.registerHelper('complianceStatus', function (critical: number, serious: number) {
  if (critical === 0 && serious === 0) return 'Compliant';
  if (critical === 0) return 'Substantially Compliant';
  if (critical <= 5) return 'Partially Compliant';
  return 'Non-Compliant';
});

/** Handlebars helper for compliance class */
Handlebars.registerHelper('complianceClass', function (critical: number, serious: number) {
  if (critical === 0 && serious === 0) return 'compliance-compliant';
  if (critical === 0) return 'compliance-substantially';
  if (critical <= 5) return 'compliance-partially';
  return 'compliance-non-compliant';
});

/** Executive report template */
const EXECUTIVE_TEMPLATE = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Accessibility Compliance Report - {{organisation.name}}</title>
  <style>${REPORT_BASE_CSS}</style>
</head>
<body>

<!-- PAGE 1: Cover -->
<div class="cover-page">
  <div style="color: #1A56A0; font-size: 14pt; font-weight: 600; margin-bottom: 16pt;">
    AccessShield India
  </div>
  <h1 class="cover-title">Accessibility Compliance Report</h1>
  <p class="cover-subtitle">Executive Summary</p>

  <div style="margin: 32pt 0;">
    <p class="cover-org-name">{{organisation.name}}</p>
    {{#if organisation.gstin}}
    <p style="font-size: 10pt; color: #6B7280;">GSTIN: {{organisation.gstin}}</p>
    {{/if}}
  </div>

  <div style="margin: 24pt 0;">
    <p class="cover-asset-name">{{asset.name}}</p>
    <p class="cover-asset-url">{{asset.url}}</p>
  </div>

  <div class="standards-row" style="justify-content: center;">
    {{#each asset.standards}}
    <span class="standard-pill">{{this}}</span>
    {{/each}}
  </div>

  <p class="cover-date">
    Scan Date: {{scan.completedAt}}<br>
    Report Generated: {{generatedAt}}<br>
    Generated By: {{generatedBy}}
  </p>

  <div class="cover-confidential">
    CONFIDENTIAL — For internal use only
  </div>
</div>

<div class="page-break"></div>

<!-- PAGE 2: Executive Summary -->
<h1>Executive Summary</h1>

<div class="score-hero">
  <div class="score-number">{{scan.score}}</div>
  <div class="score-label">Accessibility Score (out of 100)</div>
  <div class="score-delta {{deltaClass scan.scoreDelta}}">
    {{deltaDisplay scan.scoreDelta}} from previous scan
  </div>
</div>

<div class="kpi-grid">
  <div class="kpi-box kpi-box-critical">
    <div class="kpi-number">{{scan.criticalCount}}</div>
    <div class="kpi-label">Critical</div>
  </div>
  <div class="kpi-box kpi-box-serious">
    <div class="kpi-number">{{scan.seriousCount}}</div>
    <div class="kpi-label">Serious</div>
  </div>
  <div class="kpi-box kpi-box-moderate">
    <div class="kpi-number">{{scan.moderateCount}}</div>
    <div class="kpi-label">Moderate</div>
  </div>
  <div class="kpi-box kpi-box-minor">
    <div class="kpi-number">{{scan.minorCount}}</div>
    <div class="kpi-label">Minor</div>
  </div>
</div>

<h2>Summary</h2>

<p>
  This audit of <strong>{{scan.pagesScanned}} pages</strong> on {{asset.url}} identified
  <strong>{{totalViolations}} accessibility issues</strong>.
  {{#if scan.criticalCount}}
  <strong>{{scan.criticalCount}} critical issues</strong> require immediate attention
  as they block access for users with disabilities entirely.
  {{/if}}
  {{#unless scan.criticalCount}}
  No critical issues were identified that completely block access.
  {{/unless}}
</p>

{{#if previousScans.length}}
<h3>Score Trend</h3>
<svg class="trend-chart" viewBox="0 0 400 120" xmlns="http://www.w3.org/2000/svg">
  {{#each trendBars}}
  <rect class="trend-bar" x="{{x}}" y="{{y}}" width="{{width}}" height="{{height}}"/>
  <text class="trend-label" x="{{labelX}}" y="115">{{date}}</text>
  <text class="trend-score" x="{{labelX}}" y="{{scoreY}}">{{score}}</text>
  {{/each}}
</svg>
{{/if}}

<div class="page-break"></div>

<!-- PAGE 3: Standards Compliance Matrix -->
<h1>Standards Compliance Matrix</h1>

<table>
  <thead>
    <tr>
      <th style="width: 40%;">Standard</th>
      <th style="width: 30%;">Status</th>
      <th style="width: 30%;">Coverage</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>WCAG 2.2 Level AA</td>
      <td>
        <span class="compliance-badge {{complianceClass scan.criticalCount scan.seriousCount}}">
          {{complianceStatus scan.criticalCount scan.seriousCount}}
        </span>
      </td>
      <td>{{wcagCoverage}}%</td>
    </tr>
    <tr>
      <td>IS 17802 (BIS 2021)</td>
      <td>
        <span class="compliance-badge {{complianceClass scan.criticalCount scan.seriousCount}}">
          {{complianceStatus scan.criticalCount scan.seriousCount}}
        </span>
      </td>
      <td>{{is17802Coverage}}%</td>
    </tr>
    <tr>
      <td>GIGW 3.0 Guidelines</td>
      <td>
        <span class="compliance-badge {{complianceClass scan.criticalCount scan.seriousCount}}">
          {{complianceStatus scan.criticalCount scan.seriousCount}}
        </span>
      </td>
      <td>{{gigwCoverage}}%</td>
    </tr>
  </tbody>
</table>

<h3>Compliance Level Definitions</h3>
<ul>
  <li><strong>Compliant:</strong> Zero violations found for this standard</li>
  <li><strong>Substantially Compliant:</strong> Only minor/moderate issues; no serious or critical</li>
  <li><strong>Partially Compliant:</strong> Has serious violations requiring attention</li>
  <li><strong>Non-Compliant:</strong> Has critical violations blocking user access</li>
</ul>

<div class="page-break"></div>

<!-- PAGE 4: Top Issues -->
<h1>Top Issues Requiring Attention</h1>

<p>The following table shows the most impactful accessibility violations found during the audit,
sorted by severity and frequency across pages.</p>

<table>
  <thead>
    <tr>
      <th style="width: 15%;">Severity</th>
      <th style="width: 20%;">WCAG Criterion</th>
      <th style="width: 45%;">Description</th>
      <th style="width: 20%;">Pages Affected</th>
    </tr>
  </thead>
  <tbody>
    {{#each topIssues}}
    <tr>
      <td>
        <span class="severity-badge {{severityClass severity}}">{{severity}}</span>
      </td>
      <td>{{wcagCriterion}}</td>
      <td>{{description}}</td>
      <td>{{pageCount}} page(s)</td>
    </tr>
    {{/each}}
    {{#unless topIssues.length}}
    <tr>
      <td colspan="4" style="text-align: center; color: #6B7280;">
        No issues found — excellent accessibility compliance!
      </td>
    </tr>
    {{/unless}}
  </tbody>
</table>

<div class="page-break"></div>

<!-- PAGE 5: Remediation Roadmap -->
<h1>Remediation Roadmap</h1>

<h2>Quick Wins</h2>
<p>These issues can be resolved with minimal development effort:</p>

{{#if quickWins.length}}
<ul>
  {{#each quickWins}}
  <li>
    <strong>{{wcagCriterion}}:</strong> {{description}}
  </li>
  {{/each}}
</ul>
{{else}}
<p style="color: #6B7280;">No quick-win issues identified.</p>
{{/if}}

<h2>Requires Development Effort</h2>
<p>These structural issues require more significant development work:</p>

{{#if complexFixes.length}}
<ul>
  {{#each complexFixes}}
  <li>
    <strong>{{wcagCriterion}}:</strong> {{description}}
  </li>
  {{/each}}
</ul>
{{else}}
<p style="color: #6B7280;">No complex structural issues identified.</p>
{{/if}}

<div class="page-break"></div>

<!-- PAGE 6: Next Steps -->
<h1>Next Steps</h1>

{{#if certificationEligible}}
<blockquote class="callout-success">
  <strong>Certification Eligible</strong><br>
  This asset is eligible for AccessShield certification pending auditor review.
  Your organisation can display the AccessShield certification badge upon approval.
</blockquote>
{{else}}
<blockquote class="callout-warning">
  <strong>Action Required</strong><br>
  Resolve {{scan.criticalCount}} critical issue(s) to become eligible for AccessShield certification.
  Our team can provide remediation support — contact us for a consultation.
</blockquote>
{{/if}}

<h2>Recommended Actions</h2>
<ol>
  <li><strong>Address Critical Issues:</strong> Focus on the {{scan.criticalCount}} critical violations first, as these block users with disabilities entirely.</li>
  <li><strong>Review Technical Report:</strong> The detailed Technical Report provides specific code fixes for each violation.</li>
  <li><strong>Schedule Re-scan:</strong> After remediation, schedule a follow-up scan to verify fixes and update your compliance score.</li>
  <li><strong>Maintain Compliance:</strong> Enable continuous monitoring to catch new accessibility issues before they reach production.</li>
</ol>

<h2>Contact AccessShield</h2>
<p>
  For remediation support, certification queries, or to discuss enterprise compliance programs:<br>
  <strong>Email:</strong> compliance@accessshield.in<br>
  <strong>Website:</strong> https://accessshield.in
</p>

<div class="report-footer">
  <p>
    This report was generated by AccessShield India on {{generatedAt}} IST.<br>
    Report ID: {{reportId}} | Scan ID: {{scan.id}}
  </p>
  <p>
    © 2026 AccessShield India. All rights reserved.<br>
    The information contained herein is confidential and intended for the named recipient only.
  </p>
</div>

</body>
</html>
`;

/** Helper to group violations by criterion and count pages */
interface TopIssue {
  severity: string;
  wcagCriterion: string;
  description: string;
  pageCount: number;
}

function computeTopIssues(data: ReportTemplateData): TopIssue[] {
  const grouped = new Map<string, { severity: string; description: string; pages: Set<string> }>();

  for (const v of data.violations) {
    const key = `${v.wcagCriterion}:${v.severity}`;
    if (!grouped.has(key)) {
      grouped.set(key, {
        severity: v.severity,
        description: v.description,
        pages: new Set(),
      });
    }
    grouped.get(key)!.pages.add(v.pageUrl);
  }

  const issues: TopIssue[] = [];
  for (const [key, value] of grouped) {
    const [criterion] = key.split(':');
    issues.push({
      severity: value.severity,
      wcagCriterion: criterion ?? 'Unknown',
      description:
        value.description.length > 100
          ? value.description.substring(0, 100) + '...'
          : value.description,
      pageCount: value.pages.size,
    });
  }

  const severityOrder = { critical: 0, serious: 1, moderate: 2, minor: 3 };
  issues.sort((a, b) => {
    const aSev = severityOrder[a.severity as keyof typeof severityOrder] ?? 4;
    const bSev = severityOrder[b.severity as keyof typeof severityOrder] ?? 4;
    if (aSev !== bSev) return aSev - bSev;
    return b.pageCount - a.pageCount;
  });

  return issues.slice(0, 10);
}

/** Compute quick wins vs complex fixes */
function categorizeRemediations(data: ReportTemplateData): {
  quickWins: Array<{ wcagCriterion: string; description: string }>;
  complexFixes: Array<{ wcagCriterion: string; description: string }>;
} {
  const seen = new Set<string>();
  const quickWins: Array<{ wcagCriterion: string; description: string }> = [];
  const complexFixes: Array<{ wcagCriterion: string; description: string }> = [];

  const simpleRules = [
    'image-alt',
    'button-name',
    'link-name',
    'label',
    'document-title',
    'html-has-lang',
    'html-lang-valid',
    'meta-viewport',
    'duplicate-id',
  ];

  for (const v of data.violations) {
    if (seen.has(v.wcagCriterion)) continue;
    seen.add(v.wcagCriterion);

    const item = {
      wcagCriterion: v.wcagCriterion,
      description:
        v.description.length > 80 ? v.description.substring(0, 80) + '...' : v.description,
    };

    const isSimple = simpleRules.some((rule) =>
      v.description.toLowerCase().includes(rule.replace('-', ' ')),
    );

    if (isSimple || v.severity === 'minor') {
      quickWins.push(item);
    } else {
      complexFixes.push(item);
    }
  }

  return {
    quickWins: quickWins.slice(0, 5),
    complexFixes: complexFixes.slice(0, 5),
  };
}

/** Compute trend bars for SVG chart */
function computeTrendBars(data: ReportTemplateData): Array<{
  x: number;
  y: number;
  width: number;
  height: number;
  labelX: number;
  scoreY: number;
  date: string;
  score: number;
}> {
  const allScans = [
    { date: data.scan.completedAt, score: data.scan.score },
    ...data.previousScans,
  ].slice(0, 5);

  if (allScans.length === 0) return [];

  const barWidth = 50;
  const gap = 30;
  const maxHeight = 80;
  const startX = 40;

  return allScans.map((s, i) => {
    const height = (s.score / 100) * maxHeight;
    const x = startX + i * (barWidth + gap);
    const y = 90 - height;

    return {
      x,
      y,
      width: barWidth,
      height,
      labelX: x + barWidth / 2,
      scoreY: y - 5,
      date: s.date.split('/').slice(0, 2).join('/'),
      score: s.score,
    };
  });
}

/**
 * Render the Executive Summary report template.
 *
 * @param data - Complete report template data
 * @returns Rendered HTML string
 */
export function renderExecutiveTemplate(data: ReportTemplateData): string {
  const totalViolations =
    data.scan.criticalCount +
    data.scan.seriousCount +
    data.scan.moderateCount +
    data.scan.minorCount;

  const wcagCoverage = Math.max(
    0,
    Math.round(100 - (totalViolations / Math.max(data.scan.pagesScanned * 5, 1)) * 100),
  );
  const is17802Coverage = wcagCoverage;
  const gigwCoverage = Math.max(0, wcagCoverage - 5);

  const topIssues = computeTopIssues(data);
  const { quickWins, complexFixes } = categorizeRemediations(data);
  const trendBars = computeTrendBars(data);
  const certificationEligible = data.scan.score >= 80 && data.scan.criticalCount === 0;

  const templateData = {
    ...data,
    totalViolations,
    wcagCoverage,
    is17802Coverage,
    gigwCoverage,
    topIssues,
    quickWins,
    complexFixes,
    trendBars,
    certificationEligible,
    reportId: `RPT-${Date.now().toString(36).toUpperCase()}`,
  };

  const template = Handlebars.compile(EXECUTIVE_TEMPLATE);
  return template(templateData);
}
