'use client';

import { CopyButton } from '@accessshield/ui';
import { AlertTriangle } from 'lucide-react';

export interface DevPreviewBannerProps {
  className?: string;
}

/** Shown when the fix was generated by the local dev mock, not Claude. */
export function DevPreviewBanner({ className = '' }: DevPreviewBannerProps) {
  return (
    <div
      role="status"
      className={`rounded-md border border-warning-700/30 bg-warning-100 px-4 py-3 ${className}`}
    >
      <div className="flex gap-3">
        <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-warning-700" aria-hidden="true" />
        <div>
          <p className="text-sm font-semibold text-warning-700">Development preview</p>
          <p className="mt-1 text-sm leading-normal text-warning-700">
            This fix was generated locally because the API could not reach Claude. Check that{' '}
            <code className="rounded bg-white/60 px-1 py-0.5 text-xs">INTERNAL_AI_SERVICE_KEY</code>{' '}
            is in the repo root{' '}
            <code className="rounded bg-white/60 px-1 py-0.5 text-xs">.env.local</code>, the API is
            restarted, and{' '}
            <code className="rounded bg-white/60 px-1 py-0.5 text-xs">apps/ai-service</code> is
            running with a valid{' '}
            <code className="rounded bg-white/60 px-1 py-0.5 text-xs">ANTHROPIC_API_KEY</code>. Then
            click Regenerate with Claude.
          </p>
        </div>
      </div>
    </div>
  );
}

export interface FixBeforeAfterProps {
  beforeHtml: string;
  afterHtml: string;
  copyAfterLabel?: string;
}

/** Stacked before/after HTML for accessibility fixes. */
export function FixBeforeAfter({
  beforeHtml,
  afterHtml,
  copyAfterLabel = 'Copy fixed HTML',
}: FixBeforeAfterProps) {
  const unchanged = beforeHtml.trim() === afterHtml.trim();

  return (
    <div className="flex flex-col gap-4">
      <div className="rounded-md border border-border bg-bg-secondary p-4">
        <h3 className="text-sm font-semibold text-text-primary mb-2">Before (violating)</h3>
        <div className="relative">
          <pre
            className="overflow-x-auto rounded-md bg-gray-900 p-4 text-sm text-gray-100 font-mono"
            aria-label="HTML before the accessibility fix"
          >
            <code>{beforeHtml}</code>
          </pre>
          <div className="absolute top-2 right-2">
            <CopyButton text={beforeHtml} label="Copy original HTML" variant="secondary" />
          </div>
        </div>
      </div>

      <div className="rounded-md border border-success-700/30 bg-success-100/40 p-4">
        <h3 className="text-sm font-semibold text-text-primary mb-2">After (suggested fix)</h3>
        <div className="relative">
          <pre
            className="overflow-x-auto rounded-md bg-gray-900 p-4 text-sm text-gray-100 font-mono"
            aria-label="HTML after the accessibility fix"
          >
            <code>{afterHtml}</code>
          </pre>
          <div className="absolute top-2 right-2">
            <CopyButton text={afterHtml} label={copyAfterLabel} variant="secondary" />
          </div>
        </div>
        {unchanged && (
          <p className="mt-2 text-sm text-text-secondary" role="note">
            No automated change was applied for this rule. Review manually or connect the AI
            service.
          </p>
        )}
      </div>
    </div>
  );
}

/** Detect dev preview from API flag or stored explanation text. */
export function isIssueDevPreviewFix(issue: {
  aiFixDevPreview?: boolean;
  aiExplanation?: string | null;
  aiFixSuggestion?: string | null;
}): boolean {
  if (issue.aiFixDevPreview) {
    return true;
  }
  if (issue.aiExplanation?.includes('Development preview:')) {
    return true;
  }
  if (issue.aiFixSuggestion?.trimStart().startsWith('<!-- Dev preview fix')) {
    return true;
  }
  return false;
}

export function resolveFixBeforeAfter(issue: {
  elementHtml?: string | null;
  aiFixBefore?: string | null;
  aiFixAfter?: string | null;
  aiFixSuggestion?: string | null;
}): { beforeHtml: string; afterHtml: string } | null {
  const beforeHtml = issue.aiFixBefore ?? issue.elementHtml ?? null;
  const afterHtml =
    issue.aiFixAfter ??
    issue.aiFixSuggestion?.replace(/^<!-- Dev preview fix[^>]*-->\s*/i, '').trim() ??
    null;

  if (!beforeHtml || !afterHtml) {
    return null;
  }

  return { beforeHtml, afterHtml };
}
