/**
 * PDF Generator
 *
 * Converts rendered HTML into accessible PDFs using Playwright (same engine as the scanner).
 */

import { logger } from '../lib/logger';
import type { PdfGenerationOptions } from './types';

/** Default page header template for all reports */
function defaultHeaderTemplate(): string {
  return `
    <div style="width: 100%; font-size: 9px; padding: 0 18mm; display: flex; justify-content: space-between; align-items: center;">
      <div style="color: #1A56A0; font-weight: 500;">AccessShield India</div>
      <div style="color: #6B7280;">Accessibility Compliance Report</div>
    </div>
  `;
}

/** Default page footer template with page numbers */
function defaultFooterTemplate(): string {
  return `
    <div style="width: 100%; font-size: 8px; padding: 0 18mm; display: flex; justify-content: space-between; align-items: center; color: #6B7280;">
      <div>Confidential — Generated by AccessShield India</div>
      <div>Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>
    </div>
  `;
}

async function getChromium() {
  const { chromium } = await import('playwright');
  return chromium;
}

/**
 * Generate a PDF buffer from HTML content using Playwright.
 */
export async function generatePdf(html: string, options?: PdfGenerationOptions): Promise<Buffer> {
  const chromium = await getChromium();
  let browser: Awaited<ReturnType<typeof chromium.launch>> | null = null;

  try {
    logger.info('Launching Playwright for PDF generation');

    browser = await chromium.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu',
      ],
    });

    const page = await browser.newPage();

    await page.setContent(html, {
      waitUntil: 'load',
      timeout: 60000,
    });

    const pdfBuffer = await page.pdf({
      format: 'A4',
      margin: {
        top: '25mm',
        bottom: '20mm',
        left: '18mm',
        right: '18mm',
      },
      displayHeaderFooter: true,
      headerTemplate: options?.headerHtml ?? defaultHeaderTemplate(),
      footerTemplate: options?.footerHtml ?? defaultFooterTemplate(),
      printBackground: true,
    });

    logger.info({ pdfSize: pdfBuffer.length }, 'PDF generated successfully');

    return Buffer.from(pdfBuffer);
  } catch (err) {
    logger.error({ err }, 'Failed to generate PDF');
    throw new Error(
      `PDF generation failed: ${err instanceof Error ? err.message : 'Unknown error'}`,
    );
  } finally {
    if (browser) {
      try {
        await browser.close();
      } catch (closeErr) {
        logger.warn({ err: closeErr }, 'Error closing Playwright browser');
      }
    }
  }
}

/**
 * Generate PDF with custom header showing report title.
 */
export async function generatePdfWithTitle(html: string, reportTitle: string): Promise<Buffer> {
  const headerHtml = `
    <div style="width: 100%; font-size: 9px; padding: 0 18mm; display: flex; justify-content: space-between; align-items: center;">
      <div style="color: #1A56A0; font-weight: 500;">AccessShield India</div>
      <div style="color: #374151;">${reportTitle}</div>
    </div>
  `;

  return generatePdf(html, { headerHtml });
}
